apiVersion: v1
kind: Service
metadata:
  name: exporter-service
  labels:
    app: exporter-service
    service-type: citrix-adc-monitor
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: exporter-port
  selector:
    app: cpx
